---
name: java-maven workflow

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu latest
    steps:
      - name: getting sourcecode
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/java-setup@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run maven tests
        run: mvn test

