---
name: java-maven workflow

on: 
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    env: 
      APP_NAME: GitHub Actions CI

    steps:
      - name: getting sourcecode
        uses: actions/checkout@v4
      - name: setup java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: getting Application name
        run: echo "Application name is $APP_NAME"

      - name: Run maven tests
        run: mvn test

